# Files: exceptions
_COSC 101, Introduction to Computing I, 2024-11-08_

## Exceptions

*What happens if we run the following program and the user enters `one`?*


```python
num = int(input('Enter a number: '))
```

    Enter a number: one



    ---------------------------------------------------------------------------

    ValueError                                Traceback (most recent call last)

    <ipython-input-32-e5e4786827d2> in <module>
    ----> 1 num = int(input('Enter a number: '))
    

    ValueError: invalid literal for int() with base 10: 'one'


* Exception — a signal that something exceptional (i.e., unexpected or unrecoverable) has happened
* *What causes an exception?* — invalid input, invalid math (e.g., divide by zero), attempt to open a non-existent file, etc.
* *Why do we need exceptions?* — a function may not know what to do when something unexpected occurs, so it needs to notify the calling function
* Exceptions breaks a program’s flow of execution
    * Function where exception occurred stops executing — e.g., the `int` function stops executing
    * Exception is passed to calling function
        * If calling function includes code to “recover” from the exception then execution resumes in the **exception handling** code
        * Otherwise, the exception is passed to the preceding function
        * Again, if preceding function includes code to “recover” from the exception then execution resumes in the exception handling code
        * Otherwise, the exception is passed to the preceding function
        * If the program does not have any code to handle the exception, then it crashes

<p style="height:5em;"></p>

_Example_


```python
def func3():
    num = int(input('Enter a number: '))
    return num

def func2():
    input_num = func3()
    return input_num * 2

def func1():
    doubled_num = func2()
    return doubled_num * 2

def main():
    quadrupled_num = func1()
    print("Quadrupled:", quadrupled_num)

main()
```

* Flow of execution
    * `main` calls `func1` which calls `func2` which calls `func3` which calls `input` and `int`
    * `int` raises an exception
    * `func3` has no code to recover from (i.e., handle) the exception
    * Attempt to resume execution in caller (`func2`)
    * `func2` has no code to handle the exception
    * Attempt to resume execution in preceding caller (`func1`)
    * `func1` has no code to handle the exception
    * Attempt to resume execution in preceding caller (`main`)
    * `main` has no code to handle the exception
    * Attempt to resume execution outside of function
    * No code outside of function to handle the exception -> program crashes
* *How could we prevent our program from crashing if the user enters invalid input?*
    * Validate the user’s input **before** converting to an int and ask for new input if the user did not enter a valid integer
    * **Catch** the exception and ask for new input
* Best practice: do not use exception handling (`try-except`) if you can easily write code to check for and recover from errors
    * For example, validating the user's input before converting to an int is better than catching an exception

<p style="height:20em;"></p>

## Extra Practice

*Write a function called `load_data` that takes a filename and returns a list of lists, where each sublist contains the data from one row of the file. The column names should **not** be included.*


```python
def load_data(filename):
    '''
    Return a list containing rows of data from a file
    >>> load_data('people.csv')
    [['Johnson', 'Katherine', 'was a "human computer" at NASA'], 
     ['Dean', 'Mark', 'co-created the IBM personal computer'], 
     ['Berners-Lee', 'Tim', 'invented the World Wide Web'], 
     ['Hopper', 'Grace', 'found the first computer bug']]
    '''
    datafile = open(filename, 'r')
    datafile.readline() # Discard column names
    rows = []
    for line in datafile:
        values = line.strip().split(',')
        rows.append(values)
    datafile.close()
    return rows
```


```python
def load_data(filename):
    '''
    Return a list containing rows of data from a file
    >>> load_data('people.csv')
    [['Johnson', 'Katherine', 'was a "human computer" at NASA'], 
     ['Dean', 'Mark', 'co-created the IBM personal computer'], 
     ['Berners-Lee', 'Tim', 'invented the World Wide Web'], 
     ['Hopper', 'Grace', 'found the first computer bug']]
    '''

    
    
    
    
    
    
    
    
    
```

*Write a function called `ask_question` that takes the rows of data from a file of a people and asks a question using the value in the `KnownFor` column. For example, `Who co-created the IBM personal computer?`*


```python
import random

def trivia_question(data):
    '''Ask a trivia question about a randomly choosen person'''
    index = random.randrange(0, len(data))
    row = data[index]
    known_for = row[2]
    print("Who "+known_for+"?")
    guess = input("Enter a person's name: ")
    answer = row[1]+" "+row[0]
    if (answer == guess):
        print("You're correct! Well done!")
    else:
        print("Sorry, your answer is incorrect. The correct answer is: "+answer)
    
trivia_question(load_data('people.csv'))
```

    Who found the first computer bug?


    Enter a person's name:  Grace Hopper


    You're correct! Well done!


import doctest
doctest.testmod()
